library(shellpipes)
manageConflicts()
library(bbmle, mask.ok = "slice")
library(ggplot2)
library(RTMB)
library(nloptr)
loadEnvironments()
dd <- data.frame(z = c(2, 1, 4, 0, 4, 1))
fit_kappaNB(dd)
tmb_data <- list(x = dd$z)
nbEstCI()
